version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check Formatting
          command: |
              rustup component add rustfmt
              rustfmt --version
              cargo fmt --all -- --check --color=auto
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
      - run:
          name: Run all tests under miri
          command: |
              rustup toolchain install nightly --allow-downgrade -c miri
              rustup run nightly cargo miri test
      - run:
          name: Run all tests under sanitizers
          command: |
              rustup toolchain install nightly --allow-downgrade -c rust-src
              RUSTFLAGS="-Z sanitizer=address" rustup run nightly cargo -Z build-std test --target x86_64-unknown-linux-gnu
              RUSTFLAGS="-Z sanitizer=leak" rustup run nightly cargo test -Z build-std --target x86_64-unknown-linux-gnu
              RUSTFLAGS="-Z sanitizer=memory" rustup run nightly cargo test -Z build-std --target x86_64-unknown-linux-gnu
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
